name: 'scraping'
on: # rebuild any PRs and main branch changes
  schedule:
    - cron: '0 12 * * *' 
  

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          WebhookUrl: ${{ secrets.WEBHOOKURL }}
